#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Regenerate the `winapp run` contract fixture from the bundled CLI.
.DESCRIPTION
    Reads `winapp --cli-schema` from the CLI in bin/, extracts the `run`
    subcommand, and writes the trimmed fixture that run-cli-contract.test.ts
    asserts against.

    The fixture exists so the contract test can run without the CLI present
    (contributors and CI unit jobs do not all download it). Generating it here
    rather than hand-editing means it cannot drift through transcription
    mistakes, and `npm run verify-run-schema` fails when the checked-in copy no
    longer matches the CLI that is actually bundled.
.PARAMETER CliPath
    Path to winapp.exe. Defaults to the repository's bin/win-x64 copy.
.PARAMETER Check
    Compare only: exit non-zero if the fixture is stale instead of rewriting it.
.EXAMPLE
    .\scripts\sync-run-schema.ps1
    .\scripts\sync-run-schema.ps1 -Check
#>

param(
    [Parameter(Mandatory = $false)]
    [string]$CliPath,

    [Parameter(Mandatory = $false)]
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path $PSScriptRoot -Parent

if ([string]::IsNullOrWhiteSpace($CliPath)) {
    $CliPath = Join-Path $projectRoot 'bin/win-x64/winapp.exe'
}

if (-not (Test-Path $CliPath)) {
    Write-Error "winapp.exe not found at '$CliPath'. Run 'npm run download-cli:latest' first."
    exit 1
}

$fixturePath = Join-Path $projectRoot 'src/test/fixtures/run-cli-schema.json'

Write-Host "[run-schema] Reading --cli-schema from $CliPath" -ForegroundColor Blue
$raw = & $CliPath --cli-schema
if ($LASTEXITCODE -ne 0) {
    Write-Error "winapp --cli-schema failed with exit code $LASTEXITCODE"
    exit 1
}

$schema = $raw | ConvertFrom-Json
$run = $schema.subcommands.run
if (-not $run) {
    Write-Error 'The CLI schema has no "run" subcommand.'
    exit 1
}

# Ordered so the emitted JSON is stable and diffs stay readable.
$options = [ordered]@{}
foreach ($name in ($run.options | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | Sort-Object)) {
    $spec = $run.options.$name
    $entry = [ordered]@{
        valueType = $spec.valueType
        # Boolean options are bare flags; everything else consumes the next token.
        takesValue = $spec.valueType -ne 'System.Boolean'
        # An array-typed option is the CLI's way of spelling "pass me repeatedly".
        repeatable = $spec.valueType.EndsWith('[]')
    }
    if ($spec.aliases) {
        $entry['aliases'] = @($spec.aliases)
    }
    $options[$name] = $entry
}

$argumentNames = @($run.arguments | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name |
    Sort-Object { $run.arguments.$_.order })

$fixture = [ordered]@{
    _comment  = 'GENERATED by scripts/sync-run-schema.ps1 from `winapp --cli-schema`. Do not edit by hand; run `npm run sync-run-schema`.'
    cliVersion = $schema.version
    command    = 'run'
    arguments  = $argumentNames
    options    = $options
}

$json = ($fixture | ConvertTo-Json -Depth 6) + "`n"

if ($Check) {
    $current = if (Test-Path $fixturePath) { Get-Content $fixturePath -Raw } else { '' }
    if ($current -ne $json) {
        Write-Error @"
The checked-in run schema fixture does not match the bundled CLI ($($schema.version)).

The extension would ship a CLI whose run surface differs from the one the
contract test validates. Run 'npm run sync-run-schema' and review the diff:
a new option means the extension cannot reach part of the CLI, and a removed
option means the extension emits a flag the CLI will reject.
"@
        exit 1
    }
    Write-Host "[run-schema] Fixture matches bundled CLI $($schema.version)." -ForegroundColor Green
    exit 0
}

Set-Content -Path $fixturePath -Value $json -NoNewline -Encoding utf8
Write-Host "[run-schema] Wrote $fixturePath for CLI $($schema.version)." -ForegroundColor Green
